### PR TITLE
There is a comma placed in front of name in line2. Removed the comma …

### PR DESCRIPTION
**Pull request by rbijja**
…character.

Wrong syntax:
,"name" : "adodb/adodb-php",

Correct Syntax:
"name" : "adodb/adodb-php",

- [x] Ready for review
- [x] Follows CONTRIBUTING rules
- [x] Reviewed by Snyk internal team

### CODE REVIEW

**Comment by rbijja** [comment]
Please approve the change

**Comment by rbijja** [comment]
Please approve the PR

**Review by rbijja — COMMENTED** [review]
Approving the PR

**Comment by adrukh** [comment]
@rbijja this malformed json is intentional - it is used to test that the parser lib behaves in a specific way when dealing with invalid json files. See https://github.com/snyk/composer-lockfile-parser/blob/adcad9eb18293195d3cb2832ab37f528424e3cdc/test/inspect.test.ts#L124-L135 for more details.

You can help here if you'd like by making sure that this test actually asserts this behaviour, as it seems like it does not! :)

**Comment by jono-allen** [comment]
I had this issue when running flow. I solved it by adding 
```.*/node_modules/@snyk/composer-lockfile-parser/.*``` 
to my .flowconfig ignore

**Comment by lili2311** [comment]
Closing as as it is now resolved for you :)

**Pull request closed without merging**
